# Импортировать конкретные методы
imports: {SciPy: True, Euler: True, RungeKutta: True, Euler_mod: True}
# Шаг времени
STEP: 0.0001
# Шаг отрисовки(Через сколько точек времени точка отрисовывается на графике)(если 1 то не работает)
rendering_STEP: 1000
# Начальное и конечное время
T_MIN: 0
T_MAX: 1000
# Рисовать/не рисовать графики
draw_graphs: False
# Сохранение файла с данными xyz от t
report_xyz: True